[package]
name = "druid-xml-example"
version = "0.1.0"
license = "MIT"
description = "druid-xml example"
repository = "https://github.com/markijohn/druid-xml"
edition = "2018"


[dependencies]
druid-xml = {path="../druid-xml"}
druid-xml-macro = {path="../druid-xml-macro"}
druid = "0.7.0"