[package]
name = "druid-xml"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.26.0"
simplecss = "0.2.1"
druid = {version = "0.7.0"}

[feature]
dynamic = ["druid"]